---
title: "bfda_paralleled_simulations"
author: "Carolina Guidolin"
date: "2025-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("future")
install.packages("furrr")

```
```{r}
library(future)
library(furrr)

# Use all available cores
plan(multisession, workers = parallel::detectCores() - 1)

```

## Defining model parameters for bfda simulations
```{r}
# Fixed participant number, dictated by resource limitations
n_ids <- 12 

# Select possible values for intercept mean, based on what we know worked from informed_data_simulation
intercept_mean_list <- list(informed_parameters$intercept_mean)

# Select possible values for the slopes (i.e. the betas of the predictors), based on what we know worked from informed_data_simulation
e2_slope_mean_list <- list(informed_parameters$e2_slope_mean)
p4_slope_mean_list <- list(informed_parameters$p4_slope_mean)

# Fix the standard deviations for the intercept and slopes, based on what we know worked
intercept_sd <- 0.2
e2_slope_sd <- 0.2
p4_slope_sd <- 0.2

# Specify values of E2 and P4 (expressed as standardised values between -1 and 1)
e2_min_value <- -1
e2_max_value <- 1
p4_min_value <- -1
p4_max_value <- 1

# Define number of simulations to run
num_simulations <- 100 # should ideally be 1000, but simulation crashed when trying values >10 

# Define threshold for Bayes Factor 
bf_threshold <- 3
```

```{r}
# Run parallel simulations
bfda_simulated_data_parallel <- future_map_dfr(1:nrow(informed_parameters), function(row) {
  
  bf_list <- numeric(num_simulations)
  
  for (simulation in seq_len(num_simulations)) {
    
    intercept <- rnorm(n_ids, mean = informed_parameters$intercept_mean[row], sd = intercept_sd)
    e2_slope  <- rnorm(n_ids, mean = informed_parameters$e2_slope_mean[row], sd = e2_slope_sd)
    p4_slope  <- rnorm(n_ids, mean = informed_parameters$p4_slope_mean[row], sd = p4_slope_sd)
    
    sim_data <- data.frame(
      id = factor(rep(1:n_ids, each = 4)),
      e2_value = runif(4 * n_ids, e2_min_value, e2_max_value),
      p4_value = runif(4 * n_ids, p4_min_value, p4_max_value)
    )
    
    sim_data$y <- intercept[sim_data$id] +
      e2_slope[sim_data$id] * sim_data$e2_value +
      p4_slope[sim_data$id] * sim_data$p4_value +
      rnorm(n_ids * 4, mean = 0, sd = 0.3)
    
    sim_data$id0 <- sim_data$id
    
    if (anyNA(sim_data)) stop(sprintf("NA found in sim_data at row %d, simulation %d", row, simulation))
    
    bf_full <- BayesFactor::lmBF(
      y ~ e2_value + p4_value + id + id0:p4_value + id0:e2_value,
      data = sim_data,
      whichRandom = "id",
      progress = FALSE
    )
    
    bf_only_intercept <- BayesFactor::lmBF(
      y ~ id,
      data = sim_data,
      whichRandom = "id",
      progress = FALSE
    )
    
    bf_ratio <- bf_full / bf_only_intercept
    bf_list[simulation] <- as.numeric(BayesFactor::extractBF(bf_ratio)$bf)
  }
  
  TPR <- sum(bf_list > bf_threshold) / num_simulations
  
  # Return one row per `row`
  tibble::tibble(
    intercept_mean = informed_parameters$intercept_mean[row],
    e2_slope_mean  = informed_parameters$e2_slope_mean[row],
    p4_slope_mean  = informed_parameters$p4_slope_mean[row],
    TPR = TPR
  )
},
.options = furrr_options(seed = 20250602) # setting seed so we always get the same thing 
)

#head(bfda_simulated_data)

```

```{r}
# Plot heatmap
library(scales)

ggplot(bfda_simulated_data_parallel, aes(x = e2_slope_mean, y = p4_slope_mean)) +
  geom_tile(aes(fill = TPR), colour = "black") +
  scale_fill_gradient(low = "white", high = "darkgreen", name = "TPR") +
  labs(
    title = "True positive rate (TPR) for E2 and P4 slope means combinations",
    x = "E2 slope mean",
    y = "P4 slope mean"
  ) +
   scale_x_continuous(
    breaks = seq(-0.5, 0.5, by = 0.1),
    limits = c(-0.5, 0.5)
  ) +
  scale_y_continuous(
    breaks = seq(-0.5, 0.5, by = 0.1),
    limits = c(-0.5, 0.5)
  ) +
  coord_fixed(ratio = 1) +
  theme_bw() +
  theme(
    aspect.ratio = 1,
    panel.grid = element_blank(),  # clean up grid lines inside tiles
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12)
  )

```

